export const ActionUsers = {
  USERS_DATA_FETCH: "USERS_LIST_DATA_FETCH",
  USERS_LIST_DATA_RESOLVED: "USERS_LIST_DATA_RESOLVED",
  USERS_LIST_DATA_REJECTED: "USERS_LIST_DATA_REJECTED",
  USERS_ADDITIONAL_DATA_RESOLVED: "USERS_ADDITIONAL_DATA_RESOLVED",
  USERS_ADDITIONAL_DATA_REJECTED: "USERS_ADDITIONAL_DATA_REJECTED"
};
